### SIGN OUT
POST http://localhost:3000/auth/signout
content-type: application/json


### WHO AM I
GET http://localhost:3000/auth/whoami
content-type: application/json

### CREATE A NEW USER
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "merhaba@hotmail.com",
  "password" : "123123"
}

### LOGIN A USER
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "merhaba@hotmail.com",
  "password" : "123123"
}

### FIND A PARTICULAR USER BY ID
GET http://localhost:3000/auth/5
content-type: application/json

### FIND ALL USERS WITH GIVEN EMAIL
GET http://localhost:3000/auth?email=casgkdakda@hotmail.com
content-type: application/json

### DELETE A PARTICULAR USER BY ID
DELETE http://localhost:3000/auth/55

### UPDATE A PARTICULAR USER BY ID
PATCH http://localhost:3000/auth/35
content-type: application/json

{
  "email": "aaaaaaa@aaaa.com"
}

